import Head from "next/head";
import Image from "next/image";
import About from "../components/sections/Home/about";
import Contact from "../components/sections/Home/contact";
import Hero from "../components/sections/Home/hero";
import OurClient from "../components/sections/Home/ourClient";
import Facilities from "../components/sections/Home/ourFacilities";
import OurTeam from "../components/sections/Home/ourTeam";
import Service from "../components/sections/Home/service";
import Testimonial from "../components/sections/Home/testimonial";
import WorkSample from "../components/sections/Home/workSample";
import Footer from "../components/shared/footer";
import Header from "../components/shared/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sindbad IT Creative Agency & software Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <main>
        {/* main content start from here */}
        <Hero />
        <About />
        <Service />
        <Facilities />
        <WorkSample />
        <OurTeam />
        <Testimonial />
        <OurClient />
        <Contact />
      </main>
      {/* <Footer /> */}
    </>
  );
}
